name: Preveri različice Pythona

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  preveriTeste:
    runs-on: self-hosted
    steps:
      # Preveri trenutni commit
      - uses: actions/checkout@v2
        name: Preveri trenutni commit

      # Preveri ali obstaja določena .py datoteka (v tem primeru test_main.py)
      - name: Preveri obstoj datotek
        run: |
          if [ -f $GITHUB_WORKSPACE/test_main.py ]; then
            echo "Datoteka obstaja"
            echo 0 > file.txt
          else
            echo "Datoteka ne obstaja"
            echo 1 > file.txt
          fi

      # Naloži status obstoja datoteke kot artefakt
      - name: Naloži artefakt
        uses: actions/upload-artifact@v4
        with:
          name: obstaja_datoteka
          path: file.txt
          retention-days: 1

  build:
    needs: preveriTeste # Prejšnja naloga mora uspešno končati
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.11.0, 3.12.0, 3.12.1, 3.12.2] # Izvedi naslednje korake z vsemi navedenimi različicami
    steps:
      # Prenesi artefakt, ki vsebuje status obstoja datoteke
      - name: Prenesi artefakt
        uses: actions/download-artifact@v4
        with:
          name: obstaja_datoteka

      # Preveri artefakt in vrni napako, če datoteka ne obstaja
      - name: Preveri artefakt
        shell: bash
        run: |
          value=`cat file.txt`
          rm file.txt
          if [ "$value" -gt 0 ]; then
                  echo "datoteka ne obstaja"
                  exit 1
          fi

      - uses: actions/checkout@v4
      - name: Nastavi Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Namesti odvisnosti s pip
      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Poženi pytest
      - name: Poženi teste
        run: pytest