name: Check pytest  # Ime delovnega toka

on:
  push:
    branches:
      - main  # Delovni tok se sproži ob vsakem potiskanju v vejo "main"

jobs:
  test:  # Ime naloge
    runs-on: ubuntu-latest  # Delovna okolja, na katerih se bo izvajala naloga

    steps:  # Koraki naloge
    - name: Checkout repository  # Korak za preverjanje izvorne kode
      uses: actions/checkout@v2

    - name: Check for test scripts  # Preveri, ali obstaja mapo "tests"
      run: |
        if [ ! -d "tests" ]; then
          echo "Error: Test scripts directory not found." > error.txt  # Če mapa ne obstaja, ustvari napako v datoteki "error.txt"
          exit 1
        fi

    - name: Prepare testing environment  # Pripravi okolje za testiranje
      run: |
        sudo apt update  # Posodobi paketni upravitelj
        sudo apt install python3-pip -y  # Namesti Python pip
        pip3 install -r requirements.txt  # Namesti zahtevane Python knjižnice

    - name: Run tests  # Zažene teste
      run: |
        pytest

    - name: Upload error log  # Naloži datoteko z napakami
      if: failure()  
      uses: actions/upload-artifact@v2
      with:
        name: error-log  # Ime datoteke
        path: error.txt  # Pot do datoteke
