name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t yourusername/yourimage:latest .

    - name: Log in to DockerHub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u yourusername --password-stdin

    - name: Push Docker image
      run: docker push yourusername/yourimage:latest
