name: Containerisation

on:
  workflow_run:
    workflows:
      - "Tester"
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # preverjam ali 
      - uses: actions/checkout@v4
        name: Checkout latest commit

      # prijavi se v Docker
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    
      # zapakiraj aplikacijo
      - name: Packege
        run: |
            sh zapakiraj_27300.sh