name: Containerisation

on:
  workflow_run:
    workflows:
      - "Tester"
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # preverjam ali 
      - uses: actions/checkout@v4
        name: Checkout latest commit

      # prijavi se v Docker
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} > pass.txt
          cat pass.txt | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          rm pass.txt

    
      # zapakiraj aplikacijo
      - name: Packege
        run: |
            sh zapakiraj_27300.sh